from enum import Enum


class EventType(str, Enum):
    SESSION_CONNECTED = "SESSION_CONNECTED"
    SESSION_DISCONNECTED = "SESSION_DISCONNECTED"
    COMMAND_REQUESTED = "COMMAND_REQUESTED"
    COMMAND_SENT = "COMMAND_SENT"
    COMMAND_COMPLETED = "COMMAND_COMPLETED"
    COMMAND_FAILED = "COMMAND_FAILED"
    STATE_CHANGED = "STATE_CHANGED"
    SAFETY_TRIGGERED = "SAFETY_TRIGGERED"
    CAPABILITY_EVENT = "CAPABILITY_EVENT"


class MetricType(str, Enum):
    RUN_SECONDS = "RUN_SECONDS"
    COMMAND_COUNT = "COMMAND_COUNT"
    FAILED_COMMAND_COUNT = "FAILED_COMMAND_COUNT"
    SAFETY_TRIGGER_COUNT = "SAFETY_TRIGGER_COUNT"
    CAPABILITY_COUNT = "CAPABILITY_COUNT"
